openapi: "3.0.2"
info:
  title: Dummy API
  version: "1.0"

paths:
  /dummy/basic:
    post:
      summary: Post 
      description: Login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
                mobile:
                  type: string
      responses:
        "200":
          description: Logged in successfully

    get:
      summary: Get 
      description: Logout
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
      responses:
        "200":
          description: Logged out successfully

    post:
      summary: authPost 
      description: Post Basic Auth Details
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
      responses:
        "200":
          description: Updated successfully
      
    get:
      summary: getAuth
      description: Get Basic Auth Details
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
      responses:
        "200":
          description: Updated successfully
    
    patch:
      summary: Udha de isse (retained)
      description: Get Basic Details
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
      responses:
        "200":
          description: Updated successfully
